"""add_entrance_item_name

Revision ID: d29a19579537
Revises: 0b54bbfc62f1
Create Date: 2020-05-04 19:45:19.917396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29a19579537'
down_revision = '0b54bbfc62f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IndexEntrance', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('IndexEntrance', 'name')
    # ### end Alembic commands ###
